import Link from "next/link";
import { notFound } from "next/navigation";
import { ConfirmButton } from "../../_components/confirm-button";
import { SubmitButton } from "../../_components/submit-button";
import { createActivity, createCompanyContact, deleteActivity, deleteCompany, deleteCompanyContact, toggleActivity, updateCompany } from "../../actions";
import { requireWorkspace } from "@/lib/auth/workspace";
import { ACTIVITY_TYPES, ACTIVITY_TYPE_LABELS, COMPANY_STAGES, COMPANY_STAGE_LABELS, JOB_STATUS_LABELS } from "@/lib/domain/hr";

export default async function ClientDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ id }, queryParams] = await Promise.all([params, searchParams]);
  const { supabase, tenant } = await requireWorkspace();
  const [{ data: client }, { data: jobs }, contactsResult, activitiesResult] = await Promise.all([
    supabase.from("crm_companies").select("id,name,email,phone,stage,created_at").eq("id", id).eq("tenant_id", tenant.id).maybeSingle(),
    supabase.from("jobs").select("id,title,status,openings,created_at").eq("company_id", id).eq("tenant_id", tenant.id).order("created_at", { ascending: false }),
    supabase.from("crm_contacts").select("id,full_name,job_title,email,phone,decision_maker,notes").eq("company_id", id).eq("tenant_id", tenant.id).order("decision_maker", { ascending: false }).order("full_name"),
    supabase.from("activities").select("id,activity_type,subject,description,due_at,completed_at,created_at").eq("entity_type", "company").eq("entity_id", id).eq("tenant_id", tenant.id).order("created_at", { ascending: false }).limit(100),
  ]);
  if (!client) notFound();

  return <div className="workspace-content">
    <Link className="back-link" href="/app/clientes">← Voltar para clientes</Link>
    <div className="page-heading"><div><h1>{client.name}</h1><p>Cliente desde {new Date(client.created_at).toLocaleDateString("pt-BR")}.</p></div><span className={`status-badge status-${client.stage}`}>{COMPANY_STAGE_LABELS[client.stage as keyof typeof COMPANY_STAGE_LABELS] ?? client.stage}</span></div>
    {queryParams.error && <div className="notice error-notice">{queryParams.error}</div>}
    {queryParams.success && <div className="notice">{queryParams.success}</div>}
    <div className="detail-grid">
      <article className="panel"><h2>Dados comerciais</h2><p>Atualize contato e etapa do funil.</p><form className="record-form" action={updateCompany}><input type="hidden" name="id" value={client.id} /><label>Nome da empresa<input name="name" defaultValue={client.name} required /></label><label>E-mail<input name="email" type="email" defaultValue={client.email ?? ""} /></label><label>Telefone<input name="phone" defaultValue={client.phone ?? ""} /></label><label>Etapa<select name="stage" defaultValue={client.stage}>{COMPANY_STAGES.map(stage => <option key={stage} value={stage}>{COMPANY_STAGE_LABELS[stage]}</option>)}</select></label><SubmitButton>Salvar alterações</SubmitButton></form><form className="danger-zone" action={deleteCompany}><input type="hidden" name="id" value={client.id} /><div><strong>Excluir cliente</strong><small>As vagas serão mantidas como vagas internas.</small></div><ConfirmButton message="Tem certeza que deseja excluir este cliente?">Excluir</ConfirmButton></form></article>
      <article className="panel"><div className="panel-heading"><div><h2>Vagas vinculadas</h2><p>{jobs?.length ?? 0} processo(s) deste cliente.</p></div><Link className="secondary-action" href="/app/vagas">Nova vaga</Link></div>{jobs?.length ? <table className="record-list"><thead><tr><th>Vaga</th><th>Posições</th><th>Status</th><th></th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td><strong>{job.title}</strong><small>{new Date(job.created_at).toLocaleDateString("pt-BR")}</small></td><td>{job.openings}</td><td>{JOB_STATUS_LABELS[job.status as keyof typeof JOB_STATUS_LABELS] ?? job.status}</td><td><Link className="row-link" href={`/app/vagas/${job.id}`}>Abrir →</Link></td></tr>)}</tbody></table> : <div className="empty-state">Nenhuma vaga vinculada a este cliente.</div>}</article>
    </div>
    <div className="client-operations-grid">
      <article className="panel"><div className="panel-heading"><div><h2>Contatos da empresa</h2><p>{contactsResult.data?.length ?? 0} pessoa(s) mapeada(s).</p></div></div>{contactsResult.error && <div className="setup-inline">Execute a migração 004 para habilitar contatos.</div>}<form className="record-form contact-form" action={createCompanyContact}><input type="hidden" name="company_id" value={client.id} /><label>Nome<input name="full_name" required /></label><label>Cargo<input name="job_title" /></label><label>E-mail<input name="email" type="email" /></label><label>Telefone<input name="phone" /></label><label className="check-field"><input name="decision_maker" type="checkbox" /> Decisor da compra</label><label className="full-field">Observações<textarea name="notes" rows={2} /></label><SubmitButton className="full-field" pendingLabel="Adicionando...">Adicionar contato</SubmitButton></form>{contactsResult.data?.length ? <div className="contact-list">{contactsResult.data.map(contact => <div key={contact.id}><span className="member-avatar">{contact.full_name.slice(0,2).toUpperCase()}</span><div><strong>{contact.full_name}{contact.decision_maker && <em>Decisor</em>}</strong><small>{[contact.job_title,contact.email,contact.phone].filter(Boolean).join(" · ") || "Sem dados de contato"}</small>{contact.notes && <p>{contact.notes}</p>}</div><form action={deleteCompanyContact}><input type="hidden" name="contact_id" value={contact.id} /><input type="hidden" name="company_id" value={client.id} /><ConfirmButton className="remove-application" message="Remover este contato?">Remover</ConfirmButton></form></div>)}</div> : !contactsResult.error && <div className="empty-state compact">Nenhum contato cadastrado.</div>}</article>
      <article className="panel"><div className="panel-heading"><div><h2>Próximos passos</h2><p>Linha do tempo comercial deste cliente.</p></div><Link className="row-link" href="/app/agenda">Agenda completa →</Link></div><form className="record-form activity-quick-form" action={createActivity}><input type="hidden" name="return_path" value={`/app/clientes/${client.id}`} /><input type="hidden" name="entity_type" value="company" /><input type="hidden" name="entity_id" value={client.id} /><label>Tipo<select name="activity_type">{ACTIVITY_TYPES.map(type => <option key={type} value={type}>{ACTIVITY_TYPE_LABELS[type]}</option>)}</select></label><label>Assunto<input name="subject" required /></label><label>Quando<input name="due_at" type="datetime-local" /></label><label className="full-field">Detalhes<textarea name="description" rows={2} /></label><SubmitButton className="full-field" pendingLabel="Salvando...">Registrar atividade</SubmitButton></form>{activitiesResult.error && <div className="setup-inline">Execute a migração 004 para habilitar atividades.</div>}<div className="timeline-list">{activitiesResult.data?.map(activity => <div className={activity.completed_at ? "is-complete" : ""} key={activity.id}><i /><div><span>{ACTIVITY_TYPE_LABELS[activity.activity_type as keyof typeof ACTIVITY_TYPE_LABELS] ?? activity.activity_type}</span><strong>{activity.subject}</strong>{activity.description && <p>{activity.description}</p>}<time>{activity.due_at ? new Date(activity.due_at).toLocaleString("pt-BR") : new Date(activity.created_at).toLocaleString("pt-BR")}</time></div><div className="timeline-actions"><form action={toggleActivity}><input type="hidden" name="activity_id" value={activity.id} /><input type="hidden" name="completed" value={String(Boolean(activity.completed_at))} /><input type="hidden" name="return_path" value={`/app/clientes/${client.id}`} /><SubmitButton className="secondary-button" pendingLabel="...">{activity.completed_at ? "Reabrir" : "Concluir"}</SubmitButton></form><form action={deleteActivity}><input type="hidden" name="activity_id" value={activity.id} /><input type="hidden" name="return_path" value={`/app/clientes/${client.id}`} /><ConfirmButton className="remove-application" message="Excluir atividade?">Excluir</ConfirmButton></form></div></div>)}{!activitiesResult.data?.length && !activitiesResult.error && <div className="empty-state compact">Nenhuma interação registrada.</div>}</div></article>
    </div>
  </div>;
}
