import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePlanFeature } from "@/lib/subscriptions/server";
import { getAppUrl } from "@/lib/billing/config";
import { canManageEngagement, canManageEngagementActions, canViewEngagement } from "@/lib/domain/team";
import { ACTION_PLAN_STATUSES, ACTION_PLAN_STATUS_LABELS, ENGAGEMENT_CATEGORIES, ENGAGEMENT_CATEGORY_LABELS, QUESTION_TYPES, QUESTION_TYPE_LABELS, SURVEY_KIND_LABELS, SURVEY_STATUS_LABELS, enpsLabel } from "@/lib/domain/engagement";
import { CopyButton } from "../../_components/copy-button";
import { SubmitButton } from "../../_components/submit-button";
import { addEngagementQuestion, closeEngagementSurvey, createEngagementActionPlan, launchEngagementSurvey, updateEngagementActionPlan } from "../actions";

type Survey = { id: string; title: string; description: string | null; kind: string; status: string; anonymous: boolean; starts_on: string | null; ends_on: string | null; min_responses_to_display: number; public_token: string; created_at: string };
type Question = { id: string; prompt: string; question_type: string; category: string; required: boolean; options: string[]; position: number };
type ActionPlan = { id: string; title: string; description: string | null; category: string; status: string; progress: number; due_on: string | null };
type QuestionResult = { id: string; prompt: string; type: string; category: string; answer_count: number; average: number | null; texts: string[]; options: Record<string, number> };
type Summary = { locked: boolean; response_count: number; minimum: number; employee_count: number; participation: number; enps: number | null; scale_average: number | null; questions: QuestionResult[] };

function formatDate(value: string | null) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "sem data definida"; }

export default async function EngagementSurveyPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const query = await searchParams;
  const { supabase, tenant, membership } = await requirePlanFeature("/app/clima", "engagement", "Clima & engajamento");
  if (!canViewEngagement(membership.role)) return <div className="workspace-content"><div className="notice error-notice">Sua função não possui acesso aos resultados de clima.</div></div>;
  const [surveyResult, questionsResult, actionsResult] = await Promise.all([
    supabase.from("engagement_surveys").select("id,title,description,kind,status,anonymous,starts_on,ends_on,min_responses_to_display,public_token,created_at").eq("tenant_id", tenant.id).eq("id", id).maybeSingle(),
    supabase.from("engagement_questions").select("id,prompt,question_type,category,required,options,position").eq("tenant_id", tenant.id).eq("survey_id", id).order("position"),
    supabase.from("engagement_action_plans").select("id,title,description,category,status,progress,due_on").eq("tenant_id", tenant.id).eq("survey_id", id).order("created_at", { ascending: false }),
  ]);
  if (!surveyResult.data) notFound();
  const survey = surveyResult.data as Survey; const questions = (questionsResult.data ?? []) as Question[]; const actions = (actionsResult.data ?? []) as ActionPlan[];
  const summaryResult = await supabase.rpc("get_engagement_survey_summary", { p_survey_id: id });
  const summary = summaryResult.data as Summary | null;
  const publicUrl = `${getAppUrl()}/pesquisa/${survey.public_token}`;
  const canManage = canManageEngagement(membership.role); const canAct = canManageEngagementActions(membership.role);
  const statusLabel = SURVEY_STATUS_LABELS[survey.status as keyof typeof SURVEY_STATUS_LABELS] ?? survey.status;

  return <div className="workspace-content wide-content survey-detail-page">
    <div className="performance-breadcrumb"><Link href="/app/clima">← Voltar para Clima & engajamento</Link><span className={`survey-status-badge survey-status-${survey.status}`}>{statusLabel}</span></div>
    {query.error && <div className="notice error-notice">{query.error}</div>}{query.success && <div className="notice">{query.success}</div>}
    <section className="survey-detail-hero"><div><span>{SURVEY_KIND_LABELS[survey.kind as keyof typeof SURVEY_KIND_LABELS]}</span><h1>{survey.title}</h1><p>{survey.description || "Escuta estruturada para transformar experiência em decisão."}</p><small>{survey.anonymous ? "✓ Respostas anônimas" : "Respostas identificadas"} · {questions.length} pergunta(s) · {formatDate(survey.starts_on)} até {formatDate(survey.ends_on)}</small></div><div className="survey-detail-actions">{survey.status === "draft" && canManage && <form action={launchEngagementSurvey}><input type="hidden" name="survey_id" value={id} /><SubmitButton pendingLabel="Publicando...">Publicar pesquisa</SubmitButton></form>}{survey.status === "active" && canManage && <form action={closeEngagementSurvey}><input type="hidden" name="survey_id" value={id} /><SubmitButton pendingLabel="Encerrando...">Encerrar coleta</SubmitButton></form>}<Link className="secondary-button" href={publicUrl} target="_blank">Pré-visualizar ↗</Link></div></section>

    <section className="survey-share-box"><div><span className="share-icon">↗</span><div><strong>{survey.status === "active" ? "Link anônimo pronto para compartilhar" : "Link público da pesquisa"}</strong><code>{publicUrl}</code><small>O sistema bloqueia uma segunda resposta no mesmo navegador e nunca exibe resultados abaixo da amostra mínima.</small></div></div><CopyButton value={publicUrl}>Copiar link da pesquisa</CopyButton></section>

    <section className="metric-grid survey-result-metrics"><article className="metric-card"><small>Respostas</small><strong>{summary?.response_count ?? 0}</strong><em>mínimo seguro: {survey.min_responses_to_display}</em></article><article className="metric-card"><small>Participação estimada</small><strong>{summary ? `${summary.participation}%` : "0%"}</strong><em>base ativa: {summary?.employee_count ?? 0}</em></article><article className="metric-card"><small>eNPS</small><strong>{summary && !summary.locked && summary.enps !== null ? summary.enps : "—"}</strong><em>{summary?.locked ? "amostra protegida" : enpsLabel(summary?.enps ?? null)}</em></article><article className="metric-card"><small>Favorabilidade</small><strong>{summary && !summary.locked && summary.scale_average !== null ? `${summary.scale_average}/5` : "—"}</strong><em>média das escalas</em></article></section>

    {summary?.locked && <section className="sample-lock"><span>◒</span><div><strong>Privacidade antes da curiosidade</strong><p>Já existem {summary.response_count} resposta(s), mas os dados individuais permanecem ocultos até alcançar {summary.minimum}. Faltam {Math.max(0,summary.minimum-summary.response_count)} para liberar a leitura agregada.</p></div></section>}

    <section className="survey-detail-grid">
      <div className="survey-main-column">
        <article className="panel question-results-panel"><div className="panel-heading"><div><h2>Leitura por pergunta</h2><p>Priorize categorias com notas menores e transforme comentários em hipóteses.</p></div></div>{summary && !summary.locked ? <div className="question-result-list">{summary.questions.map(item => <article key={item.id}><header><span>{ENGAGEMENT_CATEGORY_LABELS[item.category as keyof typeof ENGAGEMENT_CATEGORY_LABELS] ?? item.category}</span><small>{item.answer_count} resposta(s)</small></header><h3>{item.prompt}</h3>{["scale","enps"].includes(item.type) && <div className="question-score"><strong>{item.average ?? "—"}</strong><div><i><b style={{ width: `${Math.min(100,Number(item.average ?? 0) / (item.type === "enps" ? 10 : 5) * 100)}%` }} /></i><small>média na escala {item.type === "enps" ? "0–10" : "1–5"}</small></div></div>}{item.type === "single_choice" && <div className="option-result-list">{Object.entries(item.options ?? {}).sort((a,b) => b[1]-a[1]).map(([option,total]) => <div key={option}><span>{option}</span><i><b style={{ width: `${item.answer_count ? Math.round(total/item.answer_count*100) : 0}%` }} /></i><strong>{total}</strong></div>)}</div>}{item.type === "text" && <div className="comment-list">{item.texts.map((comment,index) => <blockquote key={`${item.id}-${index}`}>“{comment}”</blockquote>)}{!item.texts.length && <small>Nenhum comentário nesta pergunta.</small>}</div>}</article>)}</div> : <div className="empty-state">Os resultados agregados aparecerão aqui quando a amostra mínima for atingida.</div>}</article>

        <article className="panel survey-question-panel"><div className="panel-heading"><div><h2>Questionário</h2><p>{survey.status === "draft" ? "Revise e acrescente perguntas antes de publicar." : "Estrutura utilizada nesta coleta."}</p></div></div><ol className="survey-question-list">{questions.map((question,index) => <li key={question.id}><span>{index+1}</span><div><strong>{question.prompt}</strong><small>{QUESTION_TYPE_LABELS[question.question_type as keyof typeof QUESTION_TYPE_LABELS]} · {ENGAGEMENT_CATEGORY_LABELS[question.category as keyof typeof ENGAGEMENT_CATEGORY_LABELS]}{question.required ? " · obrigatória" : " · opcional"}</small>{question.options?.length > 0 && <em>{question.options.join(" · ")}</em>}</div></li>)}</ol>{canManage && survey.status === "draft" && <form className="record-form question-create-form" action={addEngagementQuestion}><input type="hidden" name="survey_id" value={id} /><label className="full-field">Nova pergunta<input name="prompt" placeholder="Escreva de forma direta e sem induzir a resposta" required /></label><label>Formato<select name="question_type">{QUESTION_TYPES.map(type => <option value={type} key={type}>{QUESTION_TYPE_LABELS[type]}</option>)}</select></label><label>Categoria<select name="category">{ENGAGEMENT_CATEGORIES.map(category => <option value={category} key={category}>{ENGAGEMENT_CATEGORY_LABELS[category]}</option>)}</select></label><label className="full-field">Opções, separadas por vírgula <input name="options" placeholder="Use somente para escolha única" /></label><label className="checkbox-field"><input type="checkbox" name="required" defaultChecked /> Resposta obrigatória</label><SubmitButton className="full-field" pendingLabel="Adicionando...">Adicionar pergunta</SubmitButton></form>}</article>
      </div>

      <aside className="survey-side-column"><article className="panel action-plan-panel"><div className="panel-heading"><div><h2>Plano pós-escuta</h2><p>Escolha poucos compromissos, com dono e prazo.</p></div></div>{canAct && <form className="record-form survey-action-form" action={createEngagementActionPlan}><input type="hidden" name="survey_id" value={id} /><input type="hidden" name="return_to" value={`/app/clima/${id}`} /><label>Ação<input name="title" placeholder="O que mudará a partir deste sinal?" required /></label><label>Categoria<select name="category">{ENGAGEMENT_CATEGORIES.map(category => <option value={category} key={category}>{ENGAGEMENT_CATEGORY_LABELS[category]}</option>)}</select></label><label>Prazo<input name="due_on" type="date" /></label><label>Como faremos<textarea name="description" rows={3} /></label><SubmitButton pendingLabel="Criando...">Criar compromisso</SubmitButton></form>}<div className="action-plan-list compact-action-list">{actions.map(action => <article key={action.id}><div><span>{ENGAGEMENT_CATEGORY_LABELS[action.category as keyof typeof ENGAGEMENT_CATEGORY_LABELS]}</span><strong>{action.title}</strong><small>{action.due_on ? `Prazo ${formatDate(action.due_on)}` : "Sem prazo"}</small></div><div className="action-progress"><i><b style={{ width: `${action.progress}%` }} /></i><span>{action.progress}%</span></div>{canAct && <form action={updateEngagementActionPlan}><input type="hidden" name="action_id" value={action.id} /><input type="hidden" name="survey_id" value={id} /><select name="status" defaultValue={action.status}>{ACTION_PLAN_STATUSES.map(status => <option value={status} key={status}>{ACTION_PLAN_STATUS_LABELS[status]}</option>)}</select><input name="progress" type="number" min="0" max="100" defaultValue={action.progress} /><SubmitButton pendingLabel="...">Salvar</SubmitButton></form>}</article>)}{!actions.length && <div className="empty-state compact">Nenhum compromisso registrado.</div>}</div></article><article className="panel privacy-principles"><h2>Proteção da confiança</h2><ul><li>Respostas ficam separadas dos cadastros de pessoas.</li><li>Gestores veem somente resultados agregados.</li><li>Amostra mínima configurável evita identificação indireta.</li><li>Histórico de ações administrativas permanece auditável.</li></ul></article></aside>
    </section>
  </div>;
}
