import Link from "next/link";
import { requireWorkspace } from "@/lib/auth/workspace";
import { DATA_ENTITY_LABELS, DATA_ENTITY_TYPES, CUSTOM_FIELD_TYPES, CUSTOM_FIELD_TYPE_LABELS } from "@/lib/domain/data-foundation";
import { SubmitButton } from "../_components/submit-button";
import { ConfirmButton } from "../_components/confirm-button";
import { analyzeImport, createCustomField, deleteCustomField, mergeCandidateDuplicates } from "./actions";

export default async function DataFoundationPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const params = await searchParams; const { supabase, tenant } = await requireWorkspace();
  const [{ data: imports }, { data: fields }, duplicates] = await Promise.all([
    supabase.from("data_imports").select("id,entity_type,source_filename,status,total_rows,imported_rows,failed_rows,created_at").eq("tenant_id", tenant.id).order("created_at", { ascending: false }).limit(12),
    supabase.from("custom_field_definitions").select("id,entity_type,label,field_type,required,searchable").eq("tenant_id", tenant.id).eq("active", true).order("entity_type").order("sort_order"),
    supabase.rpc("find_candidate_duplicates", { p_tenant_id: tenant.id, p_threshold: 0.67 }),
  ]);
  return <div className="workspace-content wide-content">
    <div className="page-heading"><div><h1>Data Foundation</h1><p>Importe, personalize, encontre e consolide os dados que sustentam toda a operação.</p></div><span className="record-count">Núcleo operacional</span></div>
    {params.error && <div className="notice error-notice">{params.error}</div>}{params.success && <div className="notice">{params.success}</div>}
    <section className="data-foundation-hero"><article className="panel"><small>01 · ATIVAÇÃO</small><h2>Traga dados reais em minutos</h2><p>Importação CSV auditável, com validação linha a linha e proteção contra cadastros inválidos.</p><form className="record-form" action={analyzeImport}><label>Tipo de dado<select name="entity_type">{DATA_ENTITY_TYPES.map(type => <option key={type} value={type}>{DATA_ENTITY_LABELS[type]}</option>)}</select></label><label>Arquivo CSV<input name="file" type="file" accept=".csv,text/csv" required /></label><SubmitButton pendingLabel="Analisando arquivo...">Analisar importação</SubmitButton></form><div className="import-template-note">Use cabeçalhos como <b>nome</b>, <b>email</b>, <b>telefone</b>, <b>titulo</b>, <b>descricao</b> ou <b>data_admissao</b>.</div></article>
      <article className="panel activation-card"><small>02 · GOVERNANÇA</small><h2>Uma base que se adapta ao cliente</h2><ul><li>Campos personalizados sem deploy</li><li>Pesquisa global por todos os módulos</li><li>Timeline unificada e auditável</li><li>Detecção e união de duplicados</li></ul><Link className="secondary-action" href="/app/busca?q=">Abrir busca global →</Link></article></section>
    <section className="panel"><div className="panel-heading"><div><h2>Importações recentes</h2><p>Acompanhe o resultado e os erros de cada carga.</p></div></div>{imports?.length ? <table className="record-list"><thead><tr><th>Arquivo</th><th>Tipo</th><th>Status</th><th>Resultado</th><th></th></tr></thead><tbody>{imports.map(item => <tr key={item.id}><td><strong>{item.source_filename}</strong><small>{new Date(item.created_at).toLocaleString("pt-BR")}</small></td><td>{DATA_ENTITY_LABELS[item.entity_type as keyof typeof DATA_ENTITY_LABELS] ?? item.entity_type}</td><td><span className="status-badge">{item.status}</span></td><td>{item.imported_rows}/{item.total_rows} importados · {item.failed_rows} falhas</td><td><Link className="row-link" href={`/app/dados/importacoes/${item.id}`}>Abrir →</Link></td></tr>)}</tbody></table> : <div className="empty-state">Nenhuma importação realizada.</div>}</section>
    <section className="data-layout" id="campos"><article className="panel sticky-panel"><h2>Novo campo personalizado</h2><p>O campo passa a existir para toda a empresa, sem alterar código.</p><form className="record-form" action={createCustomField}><label>Cadastro<select name="entity_type">{DATA_ENTITY_TYPES.map(type => <option key={type} value={type}>{DATA_ENTITY_LABELS[type]}</option>)}</select></label><label>Nome do campo<input name="label" placeholder="Ex.: disponibilidade para viagens" required /></label><label>Tipo<select name="field_type">{CUSTOM_FIELD_TYPES.map(type => <option key={type} value={type}>{CUSTOM_FIELD_TYPE_LABELS[type]}</option>)}</select></label><label>Opções<textarea name="options" placeholder="Somente para seleções: Opção A, Opção B" rows={2} /></label><label className="checkbox-line"><input type="checkbox" name="required" /> Obrigatório</label><label className="checkbox-line"><input type="checkbox" name="searchable" defaultChecked /> Pesquisável</label><SubmitButton>Criar campo</SubmitButton></form></article><article className="panel"><div className="panel-heading"><div><h2>Campos ativos</h2><p>Definições reutilizadas em cadastros, filtros e relatórios.</p></div></div>{fields?.length ? <div className="custom-field-admin-list">{fields.map(field => <div key={field.id}><div><span>{DATA_ENTITY_LABELS[field.entity_type as keyof typeof DATA_ENTITY_LABELS]}</span><strong>{field.label}</strong><small>{CUSTOM_FIELD_TYPE_LABELS[field.field_type as keyof typeof CUSTOM_FIELD_TYPE_LABELS] ?? field.field_type}{field.required ? " · obrigatório" : ""}{field.searchable ? " · pesquisável" : ""}</small></div><form action={deleteCustomField}><input type="hidden" name="id" value={field.id} /><ConfirmButton message="Remover este campo e seus valores?">Excluir</ConfirmButton></form></div>)}</div> : <div className="empty-state">Crie o primeiro campo personalizado.</div>}</article></section>
    <section className="panel"><div className="panel-heading"><div><h2>Central de duplicados</h2><p>Una cadastros sem perder candidaturas, atividades ou valores personalizados.</p></div><span className="record-count">{duplicates.data?.length ?? 0} possível(is)</span></div>{duplicates.data?.length ? <div className="duplicate-list">{duplicates.data.map((item: { candidate_a:string; candidate_b:string; name_a:string; name_b:string; email_a:string; email_b:string; phone_a:string|null; phone_b:string|null; score:number; reasons:string[] }) => <article key={`${item.candidate_a}-${item.candidate_b}`}><div><strong>{item.name_a}</strong><small>{item.email_a} · {item.phone_a || "sem telefone"}</small></div><span>{Math.round(Number(item.score) * 100)}%<small>{(item.reasons as string[]).join(" · ")}</small></span><div><strong>{item.name_b}</strong><small>{item.email_b} · {item.phone_b || "sem telefone"}</small></div><form action={mergeCandidateDuplicates}><input type="hidden" name="primary_id" value={item.candidate_a} /><input type="hidden" name="duplicate_id" value={item.candidate_b} /><ConfirmButton message={`Manter ${item.name_a} e mesclar ${item.name_b}?`}>Mesclar →</ConfirmButton></form></article>)}</div> : <div className="empty-state compact">Nenhuma duplicidade relevante detectada.</div>}</section>
  </div>;
}
