import Link from "next/link";
import { ConfirmButton } from "../_components/confirm-button";
import { SubmitButton } from "../_components/submit-button";
import { requireWorkspace } from "@/lib/auth/workspace";
import { AUTOMATION_ACTION_LABELS, AUTOMATION_ACTIONS, AUTOMATION_EVENT_LABELS, AUTOMATION_EVENTS, automationSummary, type AutomationAction, type AutomationEvent } from "@/lib/domain/automations";
import { canManagePeople } from "@/lib/domain/team";
import { createAutomationRule, deleteAutomationRule, testAutomationRule, toggleAutomationRule } from "./actions";

type Rule = { id: string; template_key: string | null; name: string; description: string | null; trigger_event: AutomationEvent; action_type: AutomationAction; action_config: Record<string, string | number | null>; enabled: boolean; last_run_at: string | null; created_at: string };
type Run = { id: number; status: "succeeded" | "failed" | "skipped"; is_test: boolean; output: Record<string, unknown>; error_message: string | null; started_at: string; rule: { name?: string } | null };

export default async function AutomationsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const query = await searchParams;
  const { supabase, tenant, membership } = await requireWorkspace();
  const { data: subscription } = await supabase.from("subscriptions").select("plan:plans(name,features)").eq("tenant_id", tenant.id).maybeSingle();
  const plan = subscription?.plan as unknown as { name?: string; features?: Record<string, boolean> } | null;
  const enabledForPlan = plan?.features?.automations === true;
  const manager = canManagePeople(membership.role);
  const [rulesResult, runsResult] = enabledForPlan ? await Promise.all([
    supabase.from("automation_rules").select("id,template_key,name,description,trigger_event,action_type,action_config,enabled,last_run_at,created_at").eq("tenant_id", tenant.id).order("created_at"),
    supabase.from("automation_runs").select("id,status,is_test,output,error_message,started_at,rule:automation_rules(name)").eq("tenant_id", tenant.id).order("started_at", { ascending: false }).limit(30),
  ]) : [{ data: [], error: null }, { data: [], error: null }];
  const rules = (rulesResult.data ?? []) as unknown as Rule[];
  const runs = (runsResult.data ?? []) as unknown as Run[];
  const successfulRuns = runs.filter(run => run.status === "succeeded").length;

  return <div className="workspace-content automation-page">
    <div className="page-heading"><div><p className="page-eyebrow">OPERAÇÃO INTELIGENTE</p><h1>Automações</h1><p>Transforme eventos do CRM, ATS e Pessoas em tarefas e alertas rastreáveis.</p></div><span className="record-count">Plano {plan?.name ?? "Basic"}</span></div>
    {query.error && <div className="notice error-notice">{query.error}</div>}
    {query.success && <div className="notice">{query.success}</div>}
    {!enabledForPlan ? <section className="feature-lock-panel panel"><div className="feature-lock-orb">↯</div><small>RECURSO PRO</small><h2>Elimine tarefas manuais sem perder o controle.</h2><p>Automações conectam contratação, onboarding, ausências, agenda e notificações. Cada execução gera histórico e respeita as permissões da sua empresa.</p><div className="feature-lock-flow"><span>Candidato contratado</span><i>→</i><span>Atividade criada</span><i>→</i><span>Onboarding iniciado</span></div><Link className="primary-link-button" href="/app/assinatura">Conhecer o plano Pro →</Link></section> : <>
      <section className="metric-grid automation-metrics"><article className="metric-card"><small>Regras configuradas</small><strong>{rules.length}</strong><em>{rules.filter(rule => rule.enabled).length} ativas</em></article><article className="metric-card"><small>Execuções recentes</small><strong>{runs.length}</strong><em>últimos 30 registros</em></article><article className="metric-card"><small>Taxa de sucesso</small><strong>{runs.length ? `${Math.round(successfulRuns / runs.length * 100)}%` : "—"}</strong><em>inclui testes manuais</em></article><article className="metric-card"><small>Tempo recuperado</small><strong>{successfulRuns ? `${Math.max(1, Math.round(successfulRuns * 0.2))}h` : "0h"}</strong><em>estimativa operacional</em></article></section>
      {rulesResult.error && <div className="setup-notice"><strong>Automações aguardando configuração</strong><span>Execute a migração <code>202607220008_timeoff_automations.sql</code>.</span></div>}
      <section className="automation-layout">
        <article className="automation-rule-column"><div className="section-heading-inline"><div><h2>Regras</h2><p>Ative modelos ou crie seus próprios fluxos.</p></div><span>{rules.filter(rule => rule.enabled).length}/{rules.length} ativas</span></div><div className="automation-rule-grid">{rules.map(rule => <article className={`automation-rule-card ${rule.enabled ? "is-enabled" : ""}`} key={rule.id}><header><span className={`automation-rule-icon automation-${rule.action_type}`}>{rule.action_type === "create_activity" ? "✓" : "◇"}</span><div><small>{rule.template_key ? "MODELO PRISMAE" : "REGRA PERSONALIZADA"}</small><h3>{rule.name}</h3></div><span className={`automation-state ${rule.enabled ? "on" : ""}`}>{rule.enabled ? "Ativa" : "Pausada"}</span></header><p>{rule.description ?? automationSummary(rule.trigger_event, rule.action_type)}</p><div className="automation-flow"><span><small>QUANDO</small>{AUTOMATION_EVENT_LABELS[rule.trigger_event]}</span><i>→</i><span><small>ENTÃO</small>{AUTOMATION_ACTION_LABELS[rule.action_type]}</span></div><footer><small>{rule.last_run_at ? `Última execução ${new Date(rule.last_run_at).toLocaleString("pt-BR")}` : "Ainda não executada"}</small>{manager && <div><form action={testAutomationRule}><input type="hidden" name="rule_id" value={rule.id} /><SubmitButton className="automation-test-button" pendingLabel="Testando...">Testar</SubmitButton></form><form action={toggleAutomationRule}><input type="hidden" name="rule_id" value={rule.id} /><input type="hidden" name="enabled" value={String(rule.enabled)} /><SubmitButton className={rule.enabled ? "automation-pause-button" : "automation-enable-button"} pendingLabel="...">{rule.enabled ? "Pausar" : "Ativar"}</SubmitButton></form>{!rule.template_key && <form action={deleteAutomationRule}><input type="hidden" name="rule_id" value={rule.id} /><ConfirmButton className="automation-delete-button" message="Excluir esta automação e o histórico relacionado?">Excluir</ConfirmButton></form>}</div>}</footer></article>)}</div></article>
        {manager && <aside className="panel automation-builder"><div className="panel-heading"><div><h2>Nova automação</h2><p>Monte um fluxo funcional em menos de um minuto.</p></div></div><form className="record-form" action={createAutomationRule}><label>Nome<input name="name" required placeholder="Ex.: Avisar RH sobre contratação" /></label><label>Descrição<textarea name="description" rows={2} placeholder="Objetivo interno desta regra" /></label><div className="automation-builder-step"><span>1</span><label>Quando acontecer<select name="trigger_event" defaultValue="candidate_hired">{AUTOMATION_EVENTS.map(event => <option value={event} key={event}>{AUTOMATION_EVENT_LABELS[event]}</option>)}</select></label></div><div className="automation-builder-connector" /><div className="automation-builder-step"><span>2</span><label>Executar a ação<select name="action_type" defaultValue="create_activity">{AUTOMATION_ACTIONS.map(action => <option value={action} key={action}>{AUTOMATION_ACTION_LABELS[action]}</option>)}</select></label></div><label>Título da ação<input name="subject" placeholder="Ex.: Concluir admissão" /></label><label>Descrição da ação<textarea name="action_description" rows={3} placeholder="Contexto que aparecerá na tarefa ou notificação" /></label><div className="form-row"><label>Prazo em dias<input name="due_days" type="number" min="0" max="90" defaultValue="1" /></label><label>Destino<input name="href" defaultValue="/app/central" /></label></div><label className="inline-checkbox"><input type="checkbox" name="enabled" /> Ativar imediatamente</label><SubmitButton pendingLabel="Criando fluxo...">Criar automação</SubmitButton></form></aside>}
      </section>
      <section className="panel automation-history"><div className="panel-heading"><div><h2>Histórico de execuções</h2><p>Rastreabilidade de testes e eventos reais.</p></div></div>{runs.length ? <div className="automation-run-list">{runs.map(run => <div key={run.id}><span className={`run-status run-${run.status}`}>{run.status === "succeeded" ? "✓" : "!"}</span><div><strong>{run.rule?.name ?? "Automação"}</strong><small>{run.is_test ? "Teste manual" : "Evento real"} · {new Date(run.started_at).toLocaleString("pt-BR")}</small></div><em>{run.status === "succeeded" ? "Concluída" : run.status === "failed" ? "Falhou" : "Ignorada"}</em>{run.error_message && <p>{run.error_message}</p>}</div>)}</div> : <div className="empty-state">Teste ou ative uma regra para iniciar o histórico.</div>}</section>
    </>}
  </div>;
}
