import Link from "next/link";
import { requireWorkspace } from "@/lib/auth/workspace";
import { getAppUrl } from "@/lib/http/app-url";
import { SubmitButton } from "../_components/submit-button";
import { ConfirmButton } from "../_components/confirm-button";
import { addScreeningQuestion, createInterviewKit, createInterviewSlot, createJobOffer, deleteScreeningQuestion, updateCareerPage, updateJobPublication } from "./actions";

export default async function AtsPage({searchParams}:{searchParams:Promise<{job?:string;error?:string;success?:string}>}){
  const params=await searchParams; const {supabase,tenant}=await requireWorkspace();
  const [{data:company},{data:jobs}]=await Promise.all([supabase.from("tenants").select("name,slug,career_page_enabled,career_page_title,career_page_description,career_primary_color,career_logo_url").eq("id",tenant.id).single(),supabase.from("jobs").select("id,title,status,public_slug,published_at,employment_type,workplace_type,city,state,salary_min_cents,salary_max_cents,salary_visible,application_form_config").eq("tenant_id",tenant.id).order("created_at",{ascending:false})]);
  const selected=jobs?.find(job=>job.id===params.job)??jobs?.[0]??null;
  const [{data:questions},{data:kits},{data:slots},{data:applications}]=selected?await Promise.all([
    supabase.from("job_screening_questions").select("id,question,question_type,required,knockout,options").eq("tenant_id",tenant.id).eq("job_id",selected.id).order("sort_order"),
    supabase.from("interview_kits").select("id,name,instructions,criteria:interview_criteria(id,name,weight)").eq("tenant_id",tenant.id).eq("job_id",selected.id).eq("active",true),
    supabase.from("interview_slots").select("id,starts_at,ends_at,meeting_provider,meeting_url,bookings:interview_bookings(count)").eq("tenant_id",tenant.id).eq("job_id",selected.id).gte("starts_at",new Date().toISOString()).order("starts_at").limit(30),
    supabase.from("applications").select("id,stage,candidate:candidates(id,full_name,email)").eq("tenant_id",tenant.id).eq("job_id",selected.id).not("stage","in","(rejected,withdrawn)"),
  ]):[{data:[]},{data:[]},{data:[]},{data:[]}];
  // Consulta separada para propostas da vaga, evitando join indireto complexo.
  const applicationIds=(applications??[]).map(a=>a.id); const offerRows=applicationIds.length?(await supabase.from("job_offers").select("id,status,title,salary_cents,created_at,candidate:candidates(full_name)").eq("tenant_id",tenant.id).in("application_id",applicationIds).order("created_at",{ascending:false})).data??[]:[];
  const base=getAppUrl(); const careerUrl=`${base}/carreiras/${company?.slug}`;
  return <div className="workspace-content wide-content"><div className="page-heading"><div><h1>ATS profissional</h1><p>Carreira pública, candidatura estruturada, entrevistas consistentes, autoagendamento e propostas.</p></div>{company?.career_page_enabled&&<Link className="secondary-action" href={careerUrl} target="_blank">Ver página pública ↗</Link>}</div>{params.error&&<div className="notice error-notice">{params.error}</div>}{params.success&&<div className="notice">{params.success}</div>}
    <section className="ats-overview"><article className="panel"><small>MARCA EMPREGADORA</small><h2>Página de carreiras</h2><form className="record-form" action={updateCareerPage}><label className="checkbox-line"><input type="checkbox" name="career_page_enabled" defaultChecked={company?.career_page_enabled}/> Página pública ativa</label><label>Título<input name="career_page_title" defaultValue={company?.career_page_title??"Faça parte do nosso time"}/></label><label className="full-field">Apresentação<textarea name="career_page_description" defaultValue={company?.career_page_description??""}/></label><label>Cor da marca<input name="career_primary_color" type="color" defaultValue={company?.career_primary_color??"#3156d8"}/></label><label>URL do logo<input name="career_logo_url" type="url" defaultValue={company?.career_logo_url??""}/></label><SubmitButton className="full-field">Salvar carreira</SubmitButton></form><code className="career-url">{careerUrl}</code></article><article className="panel ats-kpis"><div><small>VAGAS PUBLICADAS</small><strong>{jobs?.filter(j=>j.published_at).length??0}</strong></div><div><small>HORÁRIOS ABERTOS</small><strong>{slots?.length??0}</strong></div><div><small>PROPOSTAS</small><strong>{offerRows.length}</strong></div><div><small>CANDIDATURAS</small><strong>{applications?.length??0}</strong></div></article></section>
    <section className="ats-workbench"><aside className="panel ats-job-selector"><h2>Vagas</h2>{jobs?.map(job=><Link className={selected?.id===job.id?"active":""} href={`/app/ats?job=${job.id}`} key={job.id}><span>{job.published_at?"●":"○"}</span><div><strong>{job.title}</strong><small>{job.status} · {job.published_at?"publicada":"interna"}</small></div></Link>)}{!jobs?.length&&<div className="empty-state">Abra uma vaga primeiro.</div>}</aside>{selected?<div className="ats-sections">
      <article className="panel"><div className="panel-heading"><div><h2>Publicação da vaga</h2><p>Transforme a requisição interna em uma experiência pública profissional.</p></div>{selected.published_at&&<Link className="row-link" target="_blank" href={`/carreiras/${company?.slug}/vagas/${selected.id}`}>Abrir vaga pública ↗</Link>}</div><form className="record-form compact-form" action={updateJobPublication}><input type="hidden" name="job_id" value={selected.id}/><input type="hidden" name="title" value={selected.title}/><label className="checkbox-line full-field"><input type="checkbox" name="published" defaultChecked={Boolean(selected.published_at)}/> Publicar na página de carreiras</label><label>Endereço público<input name="public_slug" defaultValue={selected.public_slug??""} placeholder="analista-financeiro"/></label><label>Modelo<select name="workplace_type" defaultValue={selected.workplace_type}><option value="onsite">Presencial</option><option value="hybrid">Híbrido</option><option value="remote">Remoto</option></select></label><label>Contrato<select name="employment_type" defaultValue={selected.employment_type}><option value="full_time">Tempo integral</option><option value="part_time">Meio período</option><option value="contract">Contrato</option><option value="temporary">Temporário</option><option value="internship">Estágio</option><option value="apprentice">Aprendiz</option></select></label><label>Cidade<input name="city" defaultValue={selected.city??""}/></label><label>Estado<input name="state" defaultValue={selected.state??""}/></label><label>Salário mínimo<input name="salary_min" type="number" step="0.01" defaultValue={selected.salary_min_cents?selected.salary_min_cents/100:""}/></label><label>Salário máximo<input name="salary_max" type="number" step="0.01" defaultValue={selected.salary_max_cents?selected.salary_max_cents/100:""}/></label><label className="checkbox-line"><input type="checkbox" name="salary_visible" defaultChecked={selected.salary_visible}/> Exibir salário</label><label className="checkbox-line"><input type="checkbox" name="phone_required" defaultChecked={(selected.application_form_config as {phone_required?:boolean})?.phone_required!==false}/> Telefone obrigatório</label><SubmitButton className="full-field">Salvar publicação</SubmitButton></form></article>
      <article className="panel"><div className="panel-heading"><div><h2>Perguntas de candidatura</h2><p>Valide critérios antes de consumir tempo do recrutador.</p></div></div><form className="record-form screening-form" action={addScreeningQuestion}><input type="hidden" name="job_id" value={selected.id}/><label className="full-field">Pergunta<input name="question" required/></label><label>Tipo<select name="question_type"><option value="text">Texto</option><option value="long_text">Texto longo</option><option value="boolean">Sim / não</option><option value="single_select">Seleção</option><option value="number">Número</option></select></label><label>Opções<input name="options" placeholder="Júnior, Pleno, Sênior"/></label><label>Resposta esperada<input name="expected_answer" placeholder="true ou opção"/></label><label className="checkbox-line"><input type="checkbox" name="required"/> Obrigatória</label><label className="checkbox-line"><input type="checkbox" name="knockout"/> Eliminatória</label><SubmitButton className="full-field">Adicionar pergunta</SubmitButton></form><div className="ats-item-list">{questions?.map(q=><div key={q.id}><span>{q.knockout?"ELIMINATÓRIA":q.required?"OBRIGATÓRIA":"OPCIONAL"}</span><div><strong>{q.question}</strong><small>{q.question_type}</small></div><form action={deleteScreeningQuestion}><input type="hidden" name="id" value={q.id}/><input type="hidden" name="job_id" value={selected.id}/><ConfirmButton message="Excluir pergunta?">Excluir</ConfirmButton></form></div>)}{!questions?.length&&<div className="empty-state compact">Formulário padrão, sem perguntas extras.</div>}</div></article>
      <article className="panel ats-two-columns"><div><h2>Kit de entrevista</h2><p>Defina critérios iguais para todos os candidatos.</p><form className="record-form" action={createInterviewKit}><input type="hidden" name="job_id" value={selected.id}/><label>Nome<input name="name" placeholder="Entrevista técnica" required/></label><label>Orientações<textarea name="instructions"/></label><label>Critérios, um por linha<textarea name="criteria" placeholder={'Conhecimento técnico\nComunicação\nResolução de problemas'} required/></label><SubmitButton>Criar kit</SubmitButton></form></div><div className="ats-item-list">{kits?.map(kit=><div key={kit.id}><span>KIT</span><div><strong>{kit.name}</strong><small>{(kit.criteria as Array<{id:string}>|null)?.length??0} critérios</small></div></div>)}{!kits?.length&&<div className="empty-state compact">Nenhum kit configurado.</div>}</div></article>
      <article className="panel ats-two-columns"><div><h2>Autoagendamento</h2><p>Disponibilize horários para o candidato escolher no portal.</p><form className="record-form" action={createInterviewSlot}><input type="hidden" name="job_id" value={selected.id}/><label>Início<input name="starts_at" type="datetime-local" required/></label><label>Fim<input name="ends_at" type="datetime-local" required/></label><label>Videochamada<select name="meeting_provider"><option value="manual">Link manual</option><option value="google_meet">Google Meet</option><option value="microsoft_teams">Microsoft Teams</option><option value="zoom">Zoom</option></select></label><label>Link<input name="meeting_url" type="url"/></label><SubmitButton>Disponibilizar horário</SubmitButton></form></div><div className="ats-item-list">{slots?.map(slot=><div key={slot.id}><span>{new Date(slot.starts_at).toLocaleDateString("pt-BR")}</span><div><strong>{new Date(slot.starts_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}–{new Date(slot.ends_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</strong><small>{slot.meeting_provider} · {(slot.bookings as Array<{count:number}>|null)?.[0]?.count??0} reserva(s)</small></div></div>)}{!slots?.length&&<div className="empty-state compact">Nenhum horário futuro.</div>}</div></article>
      <article className="panel ats-two-columns"><div><h2>Enviar proposta</h2><p>Formalize a oferta e disponibilize o aceite no portal.</p><form className="record-form" action={createJobOffer}><input type="hidden" name="job_id" value={selected.id}/><label className="full-field">Candidatura<select name="application_id" required><option value="">Selecione</option>{applications?.map(a=>{const c=(Array.isArray(a.candidate)?a.candidate[0]:a.candidate) as {id:string;full_name:string}|null;return <option value={a.id} key={a.id}>{c?.full_name} · {a.stage}</option>})}</select></label><label>Título<input name="title" defaultValue="Proposta de contratação"/></label><label>Salário<input name="salary" type="number" step="0.01"/></label><label>Início<input name="start_date" type="date"/></label><label>Validade<input name="expires_at" type="datetime-local"/></label><label className="full-field">Benefícios<textarea name="benefits"/></label><label className="full-field">Mensagem da proposta<textarea name="body" required placeholder="Temos o prazer de apresentar..."/></label><SubmitButton className="full-field">Criar e enviar proposta</SubmitButton></form></div><div className="ats-item-list">{offerRows.map(offer=><div key={offer.id}><span>{offer.status}</span><div><strong>{(offer.candidate as unknown as {full_name?:string}|null)?.full_name??offer.title}</strong><small>{offer.salary_cents?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(offer.salary_cents/100):"valor não informado"}</small></div></div>)}{!offerRows.length&&<div className="empty-state compact">Nenhuma proposta criada.</div>}</div></article>
    </div>:<div className="panel empty-state">Abra uma vaga para configurar o ATS profissional.</div>}</section></div>;
}
